/**
 * Fahrzeugdatenbank - Richtwerte für den deutschen Markt (Stand 2025/2026).
 *
 * Alle Werte sind Orientierungswerte auf Basis öffentlicher Hersteller- und
 * Listenpreisangaben. Sie dienen der Überschlagsrechnung und ersetzen kein
 * verbindliches Angebot. Preise = UVP-Richtwert Basisausstattung in Euro
 * inkl. MwSt., Reichweite = WLTP kombiniert, Verbrauch = WLTP inkl. Ladeverlust
 * nach Herstellerangabe (kWh/100 km).
 *
 * body:      kleinwagen | kompakt | limousine | kombi | suv | van
 * towing:    zulässige Anhängelast gebremst in kg (0 = keine AHK möglich)
 */

export const DATA_VINTAGE = 'Richtwerte Stand 2025/2026';

export const BODY_LABELS = {
  kleinwagen: 'Kleinwagen',
  kompakt: 'Kompaktklasse',
  limousine: 'Limousine',
  kombi: 'Kombi',
  suv: 'SUV / Crossover',
  van: 'Van / Bus',
};

export const vehicles = [
  {
    id: 'dacia-spring',
    brand: 'Dacia',
    model: 'Spring Electric 65',
    body: 'kleinwagen',
    price: 16900,
    batteryKwh: 26.8,
    rangeKm: 225,
    consumptionKwh100: 14.6,
    dcPeakKw: 30,
    acPeakKw: 7.4,
    seats: 4,
    bootLiters: 308,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Günstigster Einstieg, klar auf Stadt- und Pendelstrecken ausgelegt.',
  },
  {
    id: 'byd-dolphin-surf',
    brand: 'BYD',
    model: 'Dolphin Surf Boost',
    body: 'kleinwagen',
    price: 19990,
    batteryKwh: 43.2,
    rangeKm: 322,
    consumptionKwh100: 15.0,
    dcPeakKw: 85,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 308,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Viel Batterie für wenig Geld, solide Alltagsreichweite.',
  },
  {
    id: 'citroen-ec3',
    brand: 'Citroën',
    model: 'e-C3 44 kWh',
    body: 'kleinwagen',
    price: 23300,
    batteryKwh: 44,
    rangeKm: 320,
    consumptionKwh100: 16.0,
    dcPeakKw: 100,
    acPeakKw: 7.4,
    seats: 5,
    bootLiters: 310,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Komfortabel abgestimmt, hohe Sitzposition, günstige Unterhaltskosten.',
  },
  {
    id: 'fiat-grande-panda',
    brand: 'Fiat',
    model: 'Grande Panda Elettrica',
    body: 'kleinwagen',
    price: 24990,
    batteryKwh: 44,
    rangeKm: 320,
    consumptionKwh100: 16.5,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 361,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Integriertes Ladekabel an Bord, praktischer Stadt- und Zweitwagen.',
  },
  {
    id: 'renault-5',
    brand: 'Renault',
    model: '5 E-Tech 52 kWh',
    body: 'kleinwagen',
    price: 27900,
    batteryKwh: 52,
    rangeKm: 410,
    consumptionKwh100: 14.9,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 326,
    towing: 500,
    warrantyBatteryYears: 8,
    note: 'Sehr effizient, bidirektionales Laden optional, gutes Preis-Leistungs-Verhältnis.',
  },
  {
    id: 'opel-corsa-electric',
    brand: 'Opel',
    model: 'Corsa Electric 51 kWh',
    body: 'kleinwagen',
    price: 29900,
    batteryKwh: 51,
    rangeKm: 405,
    consumptionKwh100: 14.4,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 309,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Klassischer Kleinwagen mit dichtem Händlernetz und hohen Rabatten.',
  },
  {
    id: 'peugeot-e208',
    brand: 'Peugeot',
    model: 'e-208 51 kWh',
    body: 'kleinwagen',
    price: 30800,
    batteryKwh: 51,
    rangeKm: 410,
    consumptionKwh100: 14.1,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 311,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Einer der effizientesten Kleinwagen, niedrige Verbrauchskosten.',
  },
  {
    id: 'mg4',
    brand: 'MG',
    model: 'MG4 Electric Comfort 64 kWh',
    body: 'kompakt',
    price: 31990,
    batteryKwh: 64,
    rangeKm: 435,
    consumptionKwh100: 16.6,
    dcPeakKw: 140,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 363,
    towing: 500,
    warrantyBatteryYears: 7,
    note: 'Viel Auto pro Euro, Heckantrieb, 7 Jahre Garantie.',
  },
  {
    id: 'vw-id3',
    brand: 'Volkswagen',
    model: 'ID.3 Pro 59 kWh',
    body: 'kompakt',
    price: 36900,
    batteryKwh: 59,
    rangeKm: 428,
    consumptionKwh100: 15.5,
    dcPeakKw: 145,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 385,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Großes Werkstattnetz, stabiler Wiederverkauf, ausgereifte Software.',
  },
  {
    id: 'cupra-born',
    brand: 'Cupra',
    model: 'Born 59 kWh',
    body: 'kompakt',
    price: 38300,
    batteryKwh: 59,
    rangeKm: 421,
    consumptionKwh100: 15.7,
    dcPeakKw: 165,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 385,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Sportlichere Abstimmung auf ID.3-Technik.',
  },
  {
    id: 'renault-megane',
    brand: 'Renault',
    model: 'Megane E-Tech 60 kWh',
    body: 'kompakt',
    price: 38200,
    batteryKwh: 60,
    rangeKm: 450,
    consumptionKwh100: 15.7,
    dcPeakKw: 130,
    acPeakKw: 22,
    seats: 5,
    bootLiters: 440,
    towing: 500,
    warrantyBatteryYears: 8,
    note: 'Optional 22 kW AC - Vorteil beim Laden an Stadt-Ladesäulen.',
  },
  {
    id: 'volvo-ex30',
    brand: 'Volvo',
    model: 'EX30 Single Motor Extended Range',
    body: 'suv',
    price: 39790,
    batteryKwh: 69,
    rangeKm: 476,
    consumptionKwh100: 15.2,
    dcPeakKw: 153,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 318,
    towing: 1400,
    warrantyBatteryYears: 8,
    note: 'Kompakte Außenmaße, hohe Reichweite, Anhängelast trotz Kompaktformat.',
  },
  {
    id: 'hyundai-kona',
    brand: 'Hyundai',
    model: 'Kona Elektro 65 kWh',
    body: 'suv',
    price: 41900,
    batteryKwh: 65,
    rangeKm: 514,
    consumptionKwh100: 14.7,
    dcPeakKw: 102,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 466,
    towing: 750,
    warrantyBatteryYears: 8,
    note: 'Sehr effizient für ein SUV, 5 Jahre Fahrzeuggarantie ohne Kilometerbegrenzung.',
  },
  {
    id: 'kia-ev3',
    brand: 'Kia',
    model: 'EV3 Long Range 81 kWh',
    body: 'suv',
    price: 42690,
    batteryKwh: 81,
    rangeKm: 605,
    consumptionKwh100: 14.9,
    dcPeakKw: 128,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 460,
    towing: 1000,
    warrantyBatteryYears: 7,
    note: 'Höchste Reichweite in der Kompakt-SUV-Klasse, 7 Jahre Garantie.',
  },
  {
    id: 'tesla-model3',
    brand: 'Tesla',
    model: 'Model 3 RWD',
    body: 'limousine',
    price: 42990,
    batteryKwh: 60,
    rangeKm: 513,
    consumptionKwh100: 13.2,
    dcPeakKw: 170,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 594,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Effizienzbestwert der Mittelklasse, eigenes Supercharger-Netz.',
  },
  {
    id: 'opel-astra-st-electric',
    brand: 'Opel',
    model: 'Astra Sports Tourer Electric',
    body: 'kombi',
    price: 43700,
    batteryKwh: 54,
    rangeKm: 413,
    consumptionKwh100: 15.8,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 516,
    towing: 0,
    warrantyBatteryYears: 8,
    note: 'Einer der wenigen vollelektrischen Kompakt-Kombis.',
  },
  {
    id: 'skoda-elroq',
    brand: 'Skoda',
    model: 'Elroq 85',
    body: 'suv',
    price: 43900,
    batteryKwh: 82,
    rangeKm: 560,
    consumptionKwh100: 15.1,
    dcPeakKw: 175,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 470,
    towing: 1200,
    warrantyBatteryYears: 8,
    note: 'Viel Platz pro Außenmaß, hohe Ladeleistung, praxisnahe Ausstattung.',
  },
  {
    id: 'ford-explorer-ev',
    brand: 'Ford',
    model: 'Explorer EV Extended Range',
    body: 'suv',
    price: 45000,
    batteryKwh: 77,
    rangeKm: 602,
    consumptionKwh100: 14.8,
    dcPeakKw: 135,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 470,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Hohe Reichweite zum moderaten Preis, MEB-Technik.',
  },
  {
    id: 'tesla-modely',
    brand: 'Tesla',
    model: 'Model Y RWD',
    body: 'suv',
    price: 45970,
    batteryKwh: 62,
    rangeKm: 500,
    consumptionKwh100: 14.0,
    dcPeakKw: 175,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 854,
    towing: 1600,
    warrantyBatteryYears: 8,
    note: 'Sehr großer Stauraum, starke Anhängelast, dichtes Schnellladenetz.',
  },
  {
    id: 'vw-id4',
    brand: 'Volkswagen',
    model: 'ID.4 Pro 77 kWh',
    body: 'suv',
    price: 46300,
    batteryKwh: 77,
    rangeKm: 550,
    consumptionKwh100: 15.6,
    dcPeakKw: 175,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 543,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Familien-SUV mit großem Servicenetz und guter Restwertprognose.',
  },
  {
    id: 'peugeot-e5008',
    brand: 'Peugeot',
    model: 'e-5008 73 kWh (7 Sitze)',
    body: 'van',
    price: 46500,
    batteryKwh: 73,
    rangeKm: 502,
    consumptionKwh100: 17.4,
    dcPeakKw: 160,
    acPeakKw: 11,
    seats: 7,
    bootLiters: 748,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Echter 7-Sitzer mit Elektroantrieb, Alternative zum Van.',
  },
  {
    id: 'skoda-enyaq',
    brand: 'Skoda',
    model: 'Enyaq 85',
    body: 'suv',
    price: 47900,
    batteryKwh: 82,
    rangeKm: 570,
    consumptionKwh100: 15.4,
    dcPeakKw: 175,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 585,
    towing: 1200,
    warrantyBatteryYears: 8,
    note: 'Sehr großer Kofferraum, langstreckentauglich, viel Serienausstattung.',
  },
  {
    id: 'hyundai-ioniq5',
    brand: 'Hyundai',
    model: 'Ioniq 5 77 kWh',
    body: 'suv',
    price: 49900,
    batteryKwh: 77,
    rangeKm: 570,
    consumptionKwh100: 16.0,
    dcPeakKw: 233,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 527,
    towing: 1600,
    warrantyBatteryYears: 8,
    note: '800-Volt-Technik: 10-80 Prozent in rund 18 Minuten, ideal für Vielfahrer.',
  },
  {
    id: 'kia-ev6',
    brand: 'Kia',
    model: 'EV6 84 kWh',
    body: 'suv',
    price: 51990,
    batteryKwh: 84,
    rangeKm: 582,
    consumptionKwh100: 15.8,
    dcPeakKw: 258,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 490,
    towing: 1600,
    warrantyBatteryYears: 7,
    note: 'Schnellste Ladekurve im Feld, 7 Jahre Garantie.',
  },
  {
    id: 'mercedes-eqb',
    brand: 'Mercedes-Benz',
    model: 'EQB 250+ (7 Sitze optional)',
    body: 'suv',
    price: 53000,
    batteryKwh: 70.5,
    rangeKm: 536,
    consumptionKwh100: 16.2,
    dcPeakKw: 100,
    acPeakKw: 11,
    seats: 7,
    bootLiters: 495,
    towing: 1700,
    warrantyBatteryYears: 8,
    note: 'Kastige Form, dritte Sitzreihe möglich, hohe Anhängelast.',
  },
  {
    id: 'vw-idbuzz',
    brand: 'Volkswagen',
    model: 'ID. Buzz Pro 79 kWh',
    body: 'van',
    price: 54700,
    batteryKwh: 79,
    rangeKm: 423,
    consumptionKwh100: 19.9,
    dcPeakKw: 185,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 1121,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Maximales Raumangebot, dafür der höchste Verbrauch im Vergleich.',
  },
  {
    id: 'vw-id7',
    brand: 'Volkswagen',
    model: 'ID.7 Pro 77 kWh',
    body: 'limousine',
    price: 56700,
    batteryKwh: 77,
    rangeKm: 615,
    consumptionKwh100: 14.1,
    dcPeakKw: 175,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 532,
    towing: 1000,
    warrantyBatteryYears: 8,
    note: 'Langstrecken-Limousine mit sehr guter Effizienz im Verhältnis zur Größe.',
  },
  {
    id: 'bmw-i4',
    brand: 'BMW',
    model: 'i4 eDrive40',
    body: 'limousine',
    price: 58000,
    batteryKwh: 81,
    rangeKm: 590,
    consumptionKwh100: 15.2,
    dcPeakKw: 205,
    acPeakKw: 11,
    seats: 5,
    bootLiters: 470,
    towing: 1600,
    warrantyBatteryYears: 8,
    note: 'Premium-Limousine mit klassischem Fahrverhalten und hoher Reichweite.',
  },
];

export function vehicleById(id) {
  return vehicles.find((v) => v.id === id) || null;
}

export function vehicleLabel(v) {
  return `${v.brand} ${v.model}`;
}
